##
# @link https://github.com/shivammathur/setup-php
##

name: 'Quality assurance'

'on':
    push:
        branches:
            - '3.x'
            - '3.x-*'
    pull_request:
        branches:
            - '3.x'

jobs:
    run:
        strategy:
            matrix:
                operating-system:
                    - 'ubuntu-latest'
                    #- 'windows-latest'
                    #- 'macOS-latest'
                php-versions:
                    - '5.4'
                    - '5.5'
                    - '5.6'
                    - '7.0'
                    - '7.1'
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'
        name: 'PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}'
        runs-on: '${{ matrix.operating-system }}'
        env:
            COMPOSER_NO_INTERACTION: '1'
            COMPOSER_MEMORY_LIMIT: '-1'
            COMPOSER_DISABLE_XDEBUG_WARN: '1'
            COMPOSER_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        steps:
            -
                name: 'Checkout'
                uses: 'actions/checkout@v2'
            -
                name: 'Install PHP'
                uses: 'shivammathur/setup-php@v2'
                with:
                    php-version: '${{ matrix.php-versions }}'
                    extensions: 'intl, mbstring'
                env:
                    COMPOSER_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            -
                name: 'Check tools'
                run: |
                    git --version
                    php -v
                    php -m
                    composer --version
            -
                name: 'composer install'
                run: |
                    composer update
            -
                name: 'Lint - composer'
                run: |
                    composer validate
            -
                name: 'Test'
                run: |
                    "$(composer config bin-dir)/phpunit"
